### ISSUE TITLE
useradd fails

### ISSUE THREAD

**Issue by wolfpackmars2** [saltstack-formulas/gitolite-formula#8]
getting this error when adding user "git" from the gitolite pillar with the gitolite-formula.
```
2019-05-05 22:33:01,750 [salt.loaded.int.module.cmdmod:826 ][ERROR   ][17084] Command '[u'useradd', u'-s', u'/bin/zsh', u'-m', u'-d', u$
2019-05-05 22:33:01,751 [salt.loaded.int.module.cmdmod:830 ][ERROR   ][17084] stderr: useradd: group git exists - if you want to add th$
2019-05-05 22:33:01,751 [salt.loaded.int.module.cmdmod:832 ][ERROR   ][17084] retcode: 9
```

I reviewed the users formula, and it appears that the users-formula uses the following code to avoid this issue:

```
    {% if 'prime_group' in user and 'gid' in user['prime_group'] -%}
    - gid: {{ user['prime_group']['gid'] }}
    {% elif 'prime_group' in user and 'name' in user['prime_group'] %}
    - gid: {{ user['prime_group']['name'] }}
    {% else -%}
    - gid_from_name: True
    {% endif -%}
```

Effectively if the user pillar didn't specify a prime_group it will add - gid_from_name: True which causes Salt to add the -g option when creating the user, thereby avoiding the error.

useradd apparently will create the group by default if no groups for the user are specified.

The current state for the gitolite formula doesn't have any provisions for handling user groups. here:
```
{{ user.username }}_user:
  user.present:
    - name: {{ user.username }}
    - shell: {{ shell }}
    - home: {{ home }}
    - require:
      - group: {{ user.username }}_group
```

adding ' - gid_from_name: True' to the user.present state should fix this.

minion os: Ubuntu 18.04 (container)
Salt-minion version: 2019.2.0
Salt-Master version: 2019.2.0
